"""Generate 01_data_preparation.ipynb programmatically to avoid JSON-escaping issues."""
import json
import pathlib


def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def code(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


cells = []

# ── Title ──────────────────────────────────────────────────────────────────
cells.append(md([
    "# COS30019 Assignment 2B — Traffic-Based Route Guidance System\n",
    "## Notebook 01: Data Loading, Cleaning & Reshaping\n",
    "\n",
    "**Purpose:** Prepare the Boroondara SCATS traffic data for downstream ML tasks.  \n",
    "**Input:** Raw `.xls` files in `../data/`  \n",
    "**Output:** Three artefacts in `../data/processed/` — "
    "`scats_long.parquet`, `scats_wide.parquet`, `scats_metadata.csv`\n",
    "\n",
    "Run cells top-to-bottom. Each section ends with a short summary so you "
    "can verify correctness without reading the code.",
]))

# ── 1 Setup ────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 1. Setup & File Conversion\n",
    "\n",
    "The dataset is in legacy binary XLS format. `xlrd` 2.x reads XLS natively.  \n",
    "`SCATSSiteListingSpreadsheet_VicRoads.xls` contains a corrupted named-range  \n",
    "formula that causes `xlrd` to raise `AssertionError` — we monkeypatch it once  \n",
    "before importing pandas so all subsequent reads are clean.",
]))

cells.append(code([
    "# stdlib\n",
    "import datetime\n",
    "import warnings\n",
    "from pathlib import Path\n",
    "\n",
    "# Monkeypatch xlrd BEFORE pandas imports it.\n",
    "# SCATSSiteListingSpreadsheet_VicRoads.xls has a corrupted named-range\n",
    "# formula that triggers AssertionError inside xlrd.book.Book.names_epilogue.\n",
    "import xlrd\n",
    "import xlrd.book\n",
    "\n",
    "_orig_names_epilogue = xlrd.book.Book.names_epilogue\n",
    "\n",
    "\n",
    "def _patched_names_epilogue(self):\n",
    '    """Swallow AssertionError from corrupted named-range formulas; re-raise all else."""\n',
    "    try:\n",
    "        _orig_names_epilogue(self)\n",
    "    except AssertionError:\n",
    "        pass\n",
    "\n",
    "\n",
    "xlrd.book.Book.names_epilogue = _patched_names_epilogue\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.ticker as mticker\n",
    "\n",
    "warnings.filterwarnings(\"ignore\", category=UserWarning, module=\"xlrd\")\n",
    "\n",
    'print(f"pandas {pd.__version__}  numpy {np.__version__}  xlrd {xlrd.__version__}")',
]))

cells.append(code([
    "DATA_DIR      = Path(\"../data\")\n",
    "PROCESSED_DIR = DATA_DIR / \"processed\"\n",
    "PROCESSED_DIR.mkdir(exist_ok=True)\n",
    "\n",
    'SCATS_DATA_XLS  = DATA_DIR / "Scats Data October 2006.xls"\n',
    'SCATS_SITES_XLS = DATA_DIR / "SCATSSiteListingSpreadsheet_VicRoads.xls"\n',
    'TRAFFIC_CSV     = DATA_DIR / "Traffic_Count_Locations_with_LONG_LAT.csv"\n',
    "\n",
    "for path in [SCATS_DATA_XLS, SCATS_SITES_XLS, TRAFFIC_CSV]:\n",
    '    status = "OK" if path.exists() else "MISSING"\n',
    '    print(f"  [{status}] {path.name}")',
]))

# ── 2 Load ─────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 2. Load Raw Data\n",
    "\n",
    "**Sheet:** `Data` in `Scats Data October 2006.xls`  \n",
    "**Header row:** spreadsheet row 2 = `header=1` in pandas (zero-indexed).  \n",
    "Row 1 of the sheet is a merged label over the V00-V95 block; row 2 has the real column names.\n",
    "\n",
    "Expected shape: 4192 rows x 106 columns (10 metadata + 96 volume intervals).",
]))

cells.append(code([
    "raw_df = pd.read_excel(\n",
    '    SCATS_DATA_XLS,\n',
    '    sheet_name="Data",\n',
    "    header=1,        # row index 1 holds the real column names\n",
    '    engine="xlrd",\n',
    ")\n",
    "\n",
    "EXPECTED_ROWS       = 4192\n",
    "EXPECTED_SCATS      = 40\n",
    "EXPECTED_APPROACHES = 139\n",
    "N_INTERVALS         = 96   # V00-V95 fifteen-minute bins per day\n",
    "\n",
    "assert raw_df.shape[0] == EXPECTED_ROWS, (\n",
    '    f"Expected {EXPECTED_ROWS} rows, got {raw_df.shape[0]}"\n',
    ")\n",
    "\n",
    'print(f"Shape: {raw_df.shape}")\n',
    'print(f"\\nColumn names (first 12): {raw_df.columns[:12].tolist()}")\n',
    'print(f"Column names (last 5):  {raw_df.columns[-5:].tolist()}")\n',
    'print("\\nDtypes (first 12):")\n',
    "print(raw_df.dtypes[:12])\n",
    "raw_df.head(3)",
]))

cells.append(code([
    'n_scats      = raw_df["SCATS Number"].nunique()\n',
    'n_approaches = raw_df.groupby(["SCATS Number", "Location"]).ngroups\n',
    "\n",
    "assert n_scats == EXPECTED_SCATS, (\n",
    '    f"Expected {EXPECTED_SCATS} unique SCATS Numbers, found {n_scats}"\n',
    ")\n",
    "assert n_approaches == EXPECTED_APPROACHES, (\n",
    '    f"Expected {EXPECTED_APPROACHES} (SCATS, Location) pairs, found {n_approaches}"\n',
    ")\n",
    "\n",
    'print(f"Unique SCATS Numbers (intersections): {n_scats}  OK")\n',
    'print(f"Unique (SCATS Number, Location) pairs: {n_approaches}  OK")\n',
    'print(f"\\nSample SCATS Numbers: {sorted(raw_df[\'SCATS Number\'].unique())[:8]}")',
]))

cells.append(md(["### 2.1 Load SCATS Site Reference Catalogue (optional lookup)"]))

cells.append(code([
    "# xlrd monkeypatch (cell 1) is already active; this loads without error.\n",
    "sites_df = pd.read_excel(\n",
    "    SCATS_SITES_XLS,\n",
    '    sheet_name="SCATS Site Numbers",\n',
    "    header=9,   # real header on row index 9 (tenth row)\n",
    '    engine="xlrd",\n',
    ")\n",
    'sites_df["Site Number"] = sites_df["Site Number"].astype("Int64")\n',
    'print(f"SCATS site catalogue: {sites_df.shape[0]} entries")\n',
    "sites_df.head(3)",
]))

cells.append(md(["### 2.2 Traffic Count Locations (optional research extension)"]))

cells.append(code([
    "# Not used in the main pipeline. Uncomment for geographic extensions.\n",
    "# traffic_locations_df = pd.read_csv(TRAFFIC_CSV)\n",
    "# print(traffic_locations_df.shape)\n",
    "# traffic_locations_df.head(3)",
]))

# ── 3 Clean ────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 3. Clean\n",
    "\n",
    "Steps:\n",
    "1. Strip the time component from `Date` "
    "(stored as `2006-10-01 00:15:00` — the time is an XLS serial artefact).\n",
    "2. Normalise `SCATS Number` to `int`.\n",
    "3. Fix `NB_LATITUDE == 0` / `NB_LONGITUDE == 0` for site 4266.  "
    "One approach (`AUBURN_RD N of BURWOOD_RD`) has all 31 rows at (0, 0).  "
    "Fill using the modal non-zero coordinate across the site's other approaches.  "
    "Volume data is retained — the rows are valid traffic observations.\n",
    "4. Verify no V00-V95 column is entirely null for any single approach.",
]))

cells.append(code([
    "clean_df = raw_df.copy()\n",
    "\n",
    "# Strip time-of-day artefact; keep only the date.\n",
    'clean_df["Date"] = pd.to_datetime(clean_df["Date"]).dt.date\n',
    'print("Date dtype after strip:", clean_df["Date"].dtype)\n',
    'print("Date sample:", clean_df["Date"].iloc[:3].tolist())',
]))

cells.append(code([
    "# xlrd already reads SCATS Number as int64; cast is explicit for safety.\n",
    'clean_df["SCATS Number"] = clean_df["SCATS Number"].astype(int)\n',
    'print("SCATS Number dtype:", clean_df["SCATS Number"].dtype)',
]))

cells.append(code([
    "def fill_zero_coords(df: pd.DataFrame) -> pd.DataFrame:\n",
    '    """Replace (0, 0) lat/lon sentinel values with the modal non-zero\n',
    "    coordinate for the same SCATS site number.\n",
    "\n",
    "    In this dataset, coordinates of exactly 0 are unambiguously sentinels:\n",
    "    all intersections are in Melbourne, nowhere near null-island.\n",
    "    A missing approach is filled from the mode across the site's other approaches.\n",
    "    If the entire site lacks valid coords, rows are set to NaN and a\n",
    "    warning is emitted; volume data is still retained.\n",
    "\n",
    "    Args:\n",
    "        df: DataFrame with columns SCATS Number, NB_LATITUDE, NB_LONGITUDE.\n",
    "\n",
    "    Returns:\n",
    "        A copy of df with zero coords replaced.\n",
    '    """\n',
    "    df = df.copy()\n",
    '    zero_mask = (df["NB_LATITUDE"] == 0) | (df["NB_LONGITUDE"] == 0)\n',
    '    affected_sites = df.loc[zero_mask, "SCATS Number"].unique()\n',
    "\n",
    "    for site in affected_sites:\n",
    '        site_mask  = df["SCATS Number"] == site\n',
    "        valid_mask = site_mask & ~zero_mask\n",
    "        fill_lat = (\n",
    '            df.loc[valid_mask, "NB_LATITUDE"].mode()\n',
    "            if valid_mask.any() else pd.Series(dtype=float)\n",
    "        )\n",
    "        fill_lon = (\n",
    '            df.loc[valid_mask, "NB_LONGITUDE"].mode()\n',
    "            if valid_mask.any() else pd.Series(dtype=float)\n",
    "        )\n",
    "        site_zero_mask = site_mask & zero_mask\n",
    "        n_affected = site_zero_mask.sum()\n",
    "\n",
    "        if fill_lat.empty or fill_lon.empty:\n",
    "            warnings.warn(\n",
    '                f"Site {site}: {n_affected} rows have (0,0) coords and no "\n',
    '                f"non-zero reference exists for this site -- coords set to NaN."\n',
    "            )\n",
    '            df.loc[site_zero_mask, ["NB_LATITUDE", "NB_LONGITUDE"]] = np.nan\n',
    "        else:\n",
    '            df.loc[site_zero_mask, "NB_LATITUDE"]  = fill_lat.iloc[0]\n',
    '            df.loc[site_zero_mask, "NB_LONGITUDE"] = fill_lon.iloc[0]\n',
    "            print(\n",
    '                f"Site {site}: filled {n_affected} rows (0,0) -> "\n',
    '                f"({fill_lat.iloc[0]:.5f}, {fill_lon.iloc[0]:.5f})"\n',
    "            )\n",
    "\n",
    "    remaining_zeros = (\n",
    '        (df["NB_LATITUDE"] == 0) | (df["NB_LONGITUDE"] == 0)\n',
    "    ).sum()\n",
    "    assert remaining_zeros == 0, (\n",
    '        f"{remaining_zeros} rows still have (0,0) coords after fill"\n',
    "    )\n",
    "    return df\n",
    "\n",
    "\n",
    "clean_df = fill_zero_coords(clean_df)\n",
    'still_zero = ((clean_df["NB_LATITUDE"] == 0) | (clean_df["NB_LONGITUDE"] == 0)).sum()\n',
    'print(f"Rows with (0,0) coords after fix: {still_zero}  OK")',
]))

cells.append(code([
    "v_cols = [col for col in clean_df.columns if col.startswith(\"V\") and col[1:].isdigit()]\n",
    "assert len(v_cols) == N_INTERVALS, (\n",
    '    f"Expected {N_INTERVALS} volume columns, found {len(v_cols)}"\n',
    ")\n",
    "\n",
    "entirely_null = (\n",
    '    clean_df.groupby(["SCATS Number", "Location"])[v_cols]\n',
    "    .apply(lambda g: g.isnull().all(axis=0).any())\n",
    ")\n",
    "n_bad = entirely_null.sum()\n",
    "assert n_bad == 0, (\n",
    '    f"{n_bad} approaches have at least one V column entirely null"\n',
    ")\n",
    'print(f"All {N_INTERVALS} V columns have at least some data per approach  OK")',
]))

cells.append(code([
    "days_per_approach = (\n",
    '    clean_df.groupby(["SCATS Number", "Location"])["Date"]\n',
    "    .nunique()\n",
    '    .rename("n_days")\n',
    ")\n",
    'print("Days per approach summary:")\n',
    "print(days_per_approach.describe().to_string())\n",
    'print(f"\\nApproaches with <31 days: {(days_per_approach < 31).sum()}")\n',
    'print(f"Approaches with 31 days:  {(days_per_approach == 31).sum()}")\n',
    'print("\\nIncomplete approaches are NOT dropped; long format handles ragged series.")',
]))

# ── 4 Long format ──────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 4. Reshape to Long Format\n",
    "\n",
    "Melt the 96 volume columns into a tidy long DataFrame.\n",
    "\n",
    "| Column | Description |\n",
    "|---|---|\n",
    "| `scats_number` | Integer intersection ID |\n",
    "| `location` | Approach string |\n",
    "| `latitude` | Decimal degrees |\n",
    "| `longitude` | Decimal degrees |\n",
    "| `date` | `datetime.date` |\n",
    "| `interval` | Integer 0-95 (V00=0, V95=95) |\n",
    "| `time_of_day` | `datetime.time` derived from interval x 15 min |\n",
    "| `timestamp` | Full `datetime` = date + interval x 15 min |\n",
    "| `volume` | Vehicle count in that 15-minute window |\n",
    "\n",
    "Primary sort key: `(scats_number, location, timestamp)`.",
]))

cells.append(code([
    'METADATA_COLS = ["SCATS Number", "Location", "NB_LATITUDE", "NB_LONGITUDE", "Date"]\n',
    "\n",
    "long_df = (\n",
    "    clean_df[METADATA_COLS + v_cols]\n",
    "    .melt(\n",
    "        id_vars=METADATA_COLS,\n",
    "        value_vars=v_cols,\n",
    '        var_name="v_col",\n',
    '        value_name="volume",\n',
    "    )\n",
    ")\n",
    "\n",
    "# Derive integer interval index: V00 -> 0, V95 -> 95\n",
    'long_df["interval"] = long_df["v_col"].str[1:].astype(int)\n',
    'long_df.drop(columns=["v_col"], inplace=True)\n',
    "\n",
    "\n",
    "def interval_to_time(interval: int) -> datetime.time:\n",
    '    """Convert a 15-minute interval index (0-95) to a datetime.time object."""\n',
    "    total_minutes = interval * 15\n",
    "    return datetime.time(hour=total_minutes // 60, minute=total_minutes % 60)\n",
    "\n",
    "\n",
    'long_df["time_of_day"] = long_df["interval"].map(interval_to_time)\n',
    "\n",
    'long_df["timestamp"] = pd.to_datetime(\n',
    '    long_df["Date"].astype(str) + " " + long_df["time_of_day"].astype(str)\n',
    ")\n",
    "\n",
    "long_df.rename(\n",
    "    columns={\n",
    '        "SCATS Number": "scats_number",\n',
    '        "Location":     "location",\n',
    '        "NB_LATITUDE":  "latitude",\n',
    '        "NB_LONGITUDE": "longitude",\n',
    '        "Date":         "date",\n',
    "    },\n",
    "    inplace=True,\n",
    ")\n",
    "\n",
    "long_df = long_df[\n",
    '    ["scats_number", "location", "latitude", "longitude",\n',
    '     "date", "interval", "time_of_day", "timestamp", "volume"]\n',
    "]\n",
    "\n",
    'long_df.sort_values(["scats_number", "location", "timestamp"], inplace=True)\n',
    "long_df.reset_index(drop=True, inplace=True)\n",
    "\n",
    "expected_long_rows = EXPECTED_ROWS * N_INTERVALS\n",
    "assert long_df.shape[0] == expected_long_rows, (\n",
    '    f"Expected {expected_long_rows:,} rows, got {long_df.shape[0]:,}"\n',
    ")\n",
    'print(f"Long format shape: {long_df.shape}")\n',
    'print(f"Expected rows: {EXPECTED_ROWS} x {N_INTERVALS} = {expected_long_rows:,}  OK")\n',
    "long_df.head(5)",
]))

cells.append(code([
    'print("Long format dtypes:")\n',
    "print(long_df.dtypes)\n",
    'print("\\nVolume stats:")\n',
    'print(long_df["volume"].describe())',
]))

# ── 5 Wide format ──────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 5. Reshape to Per-Approach Time Series (Wide)\n",
    "\n",
    "Pivot the long format so each column is one `(scats_number, location)` approach  \n",
    "and the index is `timestamp`. This is the shape most ML time-series libraries expect.\n",
    "\n",
    "A companion list `approach_ids` holds `(scats_number, location)` tuples in column  \n",
    "order so any single series can be retrieved by index without string parsing.",
]))

cells.append(code([
    "# Build a composite column key that survives the pivot.\n",
    'long_df["approach_key"] = (\n',
    '    long_df["scats_number"].astype(str) + "__" + long_df["location"]\n',
    ")\n",
    "\n",
    "wide_df = long_df.pivot_table(\n",
    '    index="timestamp",\n',
    '    columns="approach_key",\n',
    '    values="volume",\n',
    '    aggfunc="first",\n',
    ")\n",
    "wide_df.columns.name = None  # drop axis label for cleaner display\n",
    "wide_df.sort_index(inplace=True)\n",
    "\n",
    "approach_ids = [\n",
    '    (int(col.split("__")[0]), col.split("__", 1)[1])\n',
    "    for col in wide_df.columns\n",
    "]\n",
    "\n",
    'long_df.drop(columns=["approach_key"], inplace=True)\n',
    "\n",
    "assert wide_df.shape[1] == EXPECTED_APPROACHES, (\n",
    '    f"Expected {EXPECTED_APPROACHES} approach columns, got {wide_df.shape[1]}"\n',
    ")\n",
    'print(f"Wide format shape: {wide_df.shape}")\n',
    'print(f"  Rows (timestamps):    {wide_df.shape[0]}")\n',
    'print(f"  Columns (approaches): {wide_df.shape[1]}  OK")\n',
    'print(f"\\nFirst 3 column keys: {wide_df.columns[:3].tolist()}")',
]))

cells.append(code([
    "def get_approach_series(\n",
    "    wide: pd.DataFrame,\n",
    "    ids: list,\n",
    "    scats_number: int,\n",
    "    location: str,\n",
    ") -> pd.Series:\n",
    '    """Retrieve the volume time series for a single (scats_number, location) approach.\n',
    "\n",
    "    Args:\n",
    "        wide:         Wide DataFrame with composite approach keys as columns.\n",
    "        ids:          List of (scats_number, location) tuples in column order.\n",
    "        scats_number: Integer SCATS site number.\n",
    "        location:     Exact location string as it appears in the raw data.\n",
    "\n",
    "    Returns:\n",
    "        pd.Series indexed by timestamp, values are vehicle volume counts.\n",
    "\n",
    "    Raises:\n",
    "        ValueError: If (scats_number, location) is not in ids.\n",
    '    """\n',
    "    key = (scats_number, location)\n",
    "    if key not in ids:\n",
    '        raise ValueError(f"{key} not found in approach_ids")\n',
    "    return wide.iloc[:, ids.index(key)]\n",
    "\n",
    "\n",
    "demo_series = get_approach_series(\n",
    "    wide_df, approach_ids,\n",
    "    scats_number=970,\n",
    '    location="WARRIGAL_RD N of HIGH STREET_RD",\n',
    ")\n",
    'print("Example: SCATS 970 / WARRIGAL_RD N of HIGH STREET_RD")\n',
    'print(f"  Length: {len(demo_series)}  non-null: {demo_series.notna().sum()}")\n',
    "demo_series.head(6)",
]))

# ── 6 Plots ────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 6. Sanity-Check Plots\n",
    "\n",
    "Three plots to confirm the data looks like real traffic before any modelling.",
]))

cells.append(code([
    "# 6.1 Average daily total volume by day of week\n",
    "daily_totals = (\n",
    '    long_df.groupby(["scats_number", "location", "date"])["volume"]\n',
    "    .sum()\n",
    "    .reset_index()\n",
    ")\n",
    'daily_totals["dow"] = pd.to_datetime(daily_totals["date"]).dt.dayofweek\n',
    "\n",
    'avg_by_dow = daily_totals.groupby("dow")["volume"].mean()\n',
    'day_labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]\n',
    "\n",
    "fig, ax = plt.subplots(figsize=(7, 3.5))\n",
    'ax.bar(avg_by_dow.index, avg_by_dow.values, color="steelblue", edgecolor="white")\n',
    "ax.set_xticks(range(7))\n",
    "ax.set_xticklabels(day_labels)\n",
    'ax.set_ylabel("Mean daily volume (all approaches)")\n',
    'ax.set_title("Average Daily Total Volume by Day of Week -- October 2006")\n',
    "ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f\"{x:,.0f}\"))\n",
    "ax.grid(axis=\"y\", alpha=0.3)\n",
    "fig.tight_layout()\n",
    'plt.savefig(PROCESSED_DIR / "plot_dow_volume.png", dpi=120)\n',
    "plt.show()\n",
    "\n",
    'print("Day-of-week averages:")\n',
    "for dow, label in enumerate(day_labels):\n",
    '    print(f"  {label}: {avg_by_dow.get(dow, 0):,.0f}")',
]))

cells.append(code([
    "# 6.2 Average weekday 24-hour profile for site 2000\n",
    "TARGET_SCATS    = 2000\n",
    'TARGET_LOCATION = "WARRIGAL_RD N of TOORAK_RD"\n',
    "\n",
    "approach_long = long_df[\n",
    '    (long_df["scats_number"] == TARGET_SCATS) &\n',
    '    (long_df["location"] == TARGET_LOCATION)\n',
    "]\n",
    "if approach_long.empty:\n",
    '    available = long_df[long_df["scats_number"] == TARGET_SCATS]["location"].unique()\n',
    "    TARGET_LOCATION = available[0]\n",
    '    print(f"Location not found; falling back to: {TARGET_LOCATION}")\n',
    "    approach_long = long_df[\n",
    '        (long_df["scats_number"] == TARGET_SCATS) &\n',
    '        (long_df["location"] == TARGET_LOCATION)\n',
    "    ]\n",
    "\n",
    "weekday_profile = (\n",
    '    approach_long[pd.to_datetime(approach_long["date"]).dt.dayofweek < 5]\n',
    '    .groupby("interval")["volume"]\n',
    "    .mean()\n",
    ")\n",
    "x_hours = [i * 15 / 60 for i in weekday_profile.index]\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 3.5))\n",
    'ax.plot(x_hours, weekday_profile.values, color="steelblue", linewidth=1.5)\n',
    'ax.fill_between(x_hours, weekday_profile.values, alpha=0.15, color="steelblue")\n',
    'ax.set_xlabel("Hour of day")\n',
    'ax.set_ylabel("Mean volume (15-min interval)")\n',
    'ax.set_title(f"Average Weekday Profile -- SCATS {TARGET_SCATS} / {TARGET_LOCATION}")\n',
    "ax.set_xticks(range(0, 25, 2))\n",
    "ax.set_xlim(0, 24)\n",
    'ax.axvline(8,  color="tomato",     linestyle="--", linewidth=0.8, label="08:00 AM peak")\n',
    'ax.axvline(17, color="darkorange", linestyle="--", linewidth=0.8, label="17:00 PM peak")\n',
    "ax.legend(fontsize=8)\n",
    "ax.grid(alpha=0.3)\n",
    "fig.tight_layout()\n",
    'plt.savefig(PROCESSED_DIR / "plot_weekday_profile.png", dpi=120)\n',
    "plt.show()",
]))

cells.append(code([
    "# 6.3 Heatmap: rows = day, columns = 96 intervals\n",
    "pivot_heat = approach_long.pivot_table(\n",
    '    index="date",\n',
    '    columns="interval",\n',
    '    values="volume",\n',
    '    aggfunc="first",\n',
    ")\n",
    'pivot_heat.index = pd.to_datetime(pivot_heat.index).strftime("%d %b")\n',
    "\n",
    "fig, ax = plt.subplots(figsize=(14, 5))\n",
    "im = ax.imshow(\n",
    "    pivot_heat.values,\n",
    '    aspect="auto",\n',
    '    cmap="YlOrRd",\n',
    '    interpolation="nearest",\n',
    ")\n",
    "cbar = plt.colorbar(im, ax=ax, fraction=0.02, pad=0.02)\n",
    'cbar.set_label("Volume (vehicles / 15 min)")\n',
    "\n",
    "ax.set_yticks(range(len(pivot_heat.index)))\n",
    "ax.set_yticklabels(pivot_heat.index, fontsize=7)\n",
    "\n",
    "hour_ticks = list(range(0, N_INTERVALS + 1, 4))\n",
    "ax.set_xticks(hour_ticks)\n",
    "ax.set_xticklabels(\n",
    '    [f"{h // 4:02d}:00" for h in hour_ticks],\n',
    "    rotation=45, ha=\"right\", fontsize=7,\n",
    ")\n",
    'ax.set_xlabel("Time of day")\n',
    'ax.set_ylabel("Day of October 2006")\n',
    'ax.set_title(f"Volume Heatmap -- SCATS {TARGET_SCATS} / {TARGET_LOCATION}")\n',
    "fig.tight_layout()\n",
    'plt.savefig(PROCESSED_DIR / "plot_heatmap.png", dpi=120)\n',
    "plt.show()\n",
    'print(f"Heatmap: {pivot_heat.shape[0]} days x {pivot_heat.shape[1]} intervals")',
]))

# ── 7 Split helper ─────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 7. Train / Val / Test Split Helper\n",
    "\n",
    "**Assumption:** Traffic volume is a time series — shuffling leaks future data into  \n",
    "training.  Splits are strictly chronological: earliest observations go to train, latest to test.\n",
    "\n",
    "Default fractions for ~31 days of 15-minute data:\n",
    "- **Train:** first ~21 days (70 %)\n",
    "- **Val:**   next ~5 days (15 %)\n",
    "- **Test:**  final ~5 days (15 %)",
]))

cells.append(code([
    "def make_splits(\n",
    "    series: np.ndarray,\n",
    "    train_frac: float = 0.70,\n",
    "    val_frac: float   = 0.15,\n",
    ") -> tuple[np.ndarray, np.ndarray, np.ndarray]:\n",
    '    """Split a 1-D time series chronologically into train / val / test arrays.\n',
    "\n",
    "    No shuffling is performed.  Shuffling a time series leaks future\n",
    "    observations into training and produces optimistic, unrealistic metrics.\n",
    "\n",
    "    Args:\n",
    "        series:     1-D numpy array of ordered observations.\n",
    "        train_frac: Fraction for training  (default 0.70 -> ~21 days).\n",
    "        val_frac:   Fraction for validation (default 0.15 -> ~5 days).\n",
    "                    Test fraction is 1 - train_frac - val_frac.\n",
    "\n",
    "    Returns:\n",
    "        (train_arr, val_arr, test_arr) as numpy arrays.\n",
    "\n",
    "    Raises:\n",
    "        ValueError: If fractions are invalid or series is not 1-D.\n",
    '    """\n',
    "    if series.ndim != 1:\n",
    '        raise ValueError(f"series must be 1-D, got shape {series.shape}")\n',
    "    if train_frac + val_frac >= 1.0:\n",
    "        raise ValueError(\n",
    '            f"train_frac + val_frac must be < 1.0, got {train_frac + val_frac:.3f}"\n',
    "        )\n",
    "    n = len(series)\n",
    "    train_end = int(n * train_frac)\n",
    "    val_end   = int(n * (train_frac + val_frac))\n",
    "    return series[:train_end], series[train_end:val_end], series[val_end:]\n",
    "\n",
    "\n",
    "example_values = demo_series.dropna().values\n",
    "train_arr, val_arr, test_arr = make_splits(example_values)\n",
    "\n",
    "total = len(example_values)\n",
    'print(f"Series length: {total} intervals ({total / N_INTERVALS:.1f} days)")\n',
    'print(f"  Train: {len(train_arr):>5}  ({len(train_arr) / N_INTERVALS:.1f} days)")\n',
    'print(f"  Val:   {len(val_arr):>5}  ({len(val_arr) / N_INTERVALS:.1f} days)")\n',
    'print(f"  Test:  {len(test_arr):>5}  ({len(test_arr) / N_INTERVALS:.1f} days)")\n',
    "assert len(train_arr) + len(val_arr) + len(test_arr) == total",
]))

# ── 8 Windows helper ───────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 8. Sliding-Window Helper\n",
    "\n",
    "Converts a 1-D volume series into supervised `(X, y)` arrays for sequence models  \n",
    "(LSTM, GRU, etc.).\n",
    "\n",
    "- `lookback = 12` -> 3 hours of history (12 x 15 min) as model input\n",
    "- `horizon  = 1`  -> predict the next single 15-minute interval",
]))

cells.append(code([
    "def make_windows(\n",
    "    series: np.ndarray,\n",
    "    lookback: int = 12,\n",
    "    horizon:  int = 1,\n",
    ") -> tuple[np.ndarray, np.ndarray]:\n",
    '    """Convert a 1-D time series into sliding-window (X, y) arrays.\n',
    "\n",
    "    Each sample uses `lookback` consecutive observations as features and\n",
    "    `horizon` subsequent observations as targets.  Windows advance one step\n",
    "    at a time (stride = 1).\n",
    "\n",
    "    Args:\n",
    "        series:   1-D numpy array of ordered observations.  Should not\n",
    "                  contain NaN values -- call .dropna() first if needed.\n",
    "        lookback: Number of past intervals used as model input.\n",
    "                  Default 12 = 3 hours at 15-minute resolution.\n",
    "                  Increase for longer-range models (e.g. 96 for one full day).\n",
    "        horizon:  Number of future intervals to predict.  Default 1 = the\n",
    "                  next 15-minute interval.  Increase for multi-step forecasts.\n",
    "\n",
    "    Returns:\n",
    "        Tuple (X, y) where:\n",
    "            X.shape == (n_samples, lookback)\n",
    "            y.shape == (n_samples, horizon)\n",
    "        n_samples = len(series) - lookback - horizon + 1\n",
    "\n",
    "    Raises:\n",
    "        ValueError: If series is not 1-D or too short for lookback + horizon.\n",
    '    """\n',
    "    if series.ndim != 1:\n",
    '        raise ValueError(f"series must be 1-D, got shape {series.shape}")\n',
    "    if len(series) < lookback + horizon:\n",
    "        raise ValueError(\n",
    '            f"series length {len(series)} < lookback+horizon={lookback + horizon}"\n',
    "        )\n",
    "    n_samples = len(series) - lookback - horizon + 1\n",
    "    x_list = [series[i : i + lookback]                  for i in range(n_samples)]\n",
    "    y_list = [series[i + lookback : i + lookback + horizon] for i in range(n_samples)]\n",
    "    return np.array(x_list), np.array(y_list)\n",
    "\n",
    "\n",
    "X_demo, y_demo = make_windows(train_arr, lookback=12, horizon=1)\n",
    'print("make_windows demo (lookback=12, horizon=1):")\n',
    'print(f"  Input length: {len(train_arr)}")\n',
    'print(f"  X.shape: {X_demo.shape}   (n_samples, lookback)")\n',
    'print(f"  y.shape: {y_demo.shape}   (n_samples, horizon)")\n',
    'print(f"  X[0]: {X_demo[0]}")\n',
    'print(f"  y[0]: {y_demo[0]}")',
]))

# ── 9 Save ─────────────────────────────────────────────────────────────────
cells.append(md([
    "---\n",
    "## 9. Save Outputs\n",
    "\n",
    "Three artefacts written to `../data/processed/`:\n",
    "\n",
    "| File | Description |\n",
    "|---|---|\n",
    "| `scats_long.parquet` | Long-format DataFrame -- canonical input for all downstream tasks |\n",
    "| `scats_wide.parquet` | Wide per-approach DataFrame -- direct ML input |\n",
    "| `scats_metadata.csv` | One row per approach with coordinate and volume summary stats |",
]))

cells.append(code([
    "# Build metadata table: one row per (scats_number, location) approach\n",
    "meta_agg = (\n",
    '    long_df.groupby(["scats_number", "location", "latitude", "longitude"])\n',
    '    .agg(total_volume=("volume", "sum"))\n',
    "    .reset_index()\n",
    ")\n",
    "\n",
    "days_lookup = days_per_approach.reset_index()\n",
    'days_lookup.columns = ["scats_number", "location", "n_days"]\n',
    'days_lookup["scats_number"] = days_lookup["scats_number"].astype(int)\n',
    "\n",
    'metadata_df = meta_agg.merge(days_lookup, on=["scats_number", "location"], how="left")\n',
    'metadata_df["mean_daily_volume"] = (\n',
    '    metadata_df["total_volume"] / metadata_df["n_days"]\n',
    ").round(2)\n",
    "\n",
    "metadata_df = metadata_df[\n",
    '    ["scats_number", "location", "latitude", "longitude",\n',
    '     "n_days", "mean_daily_volume"]\n',
    '].sort_values(["scats_number", "location"]).reset_index(drop=True)\n',
    "\n",
    'print(f"Metadata rows: {len(metadata_df)}  (expected {EXPECTED_APPROACHES})")\n',
    "metadata_df.head(5)",
]))

cells.append(code([
    "# Parquet requires serialisable types: convert date and time_of_day to str.\n",
    "long_save = long_df.copy()\n",
    'long_save["date"]        = long_save["date"].astype(str)\n',
    'long_save["time_of_day"] = long_save["time_of_day"].astype(str)\n',
    "\n",
    'long_save.to_parquet(PROCESSED_DIR / "scats_long.parquet", index=False)\n',
    'wide_df.to_parquet(PROCESSED_DIR / "scats_wide.parquet")\n',
    'metadata_df.to_csv(PROCESSED_DIR / "scats_metadata.csv", index=False)\n',
    "\n",
    'print("Artefacts written:")\n',
    "for fpath in sorted(PROCESSED_DIR.iterdir()):\n",
    '    if fpath.suffix in (".parquet", ".csv"):\n',
    "        size_kb = fpath.stat().st_size / 1024\n",
    '        print(f"  {fpath.name:<32} {size_kb:>8.1f} KB")',
]))

cells.append(code([
    "# Round-trip verification\n",
    'rt_long = pd.read_parquet(PROCESSED_DIR / "scats_long.parquet")\n',
    'rt_wide = pd.read_parquet(PROCESSED_DIR / "scats_wide.parquet")\n',
    'rt_meta = pd.read_csv(PROCESSED_DIR / "scats_metadata.csv")\n',
    "\n",
    "assert rt_long.shape == long_save.shape,   \"scats_long round-trip shape mismatch\"\n",
    "assert rt_wide.shape == wide_df.shape,     \"scats_wide round-trip shape mismatch\"\n",
    "assert rt_meta.shape == metadata_df.shape, \"scats_metadata round-trip shape mismatch\"\n",
    "\n",
    'print("Round-trip verification:")\n',
    'print(f"  scats_long.parquet  {rt_long.shape}   OK")\n',
    'print(f"  scats_wide.parquet  {rt_wide.shape}   OK")\n',
    'print(f"  scats_metadata.csv  {rt_meta.shape}   OK")\n',
    'print("\\nAll artefacts verified. Notebook complete.")',
]))

# ── Write notebook ─────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out_path = pathlib.Path(__file__).parent / "notebooks" / "01_data_preparation.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)
print("Written:", out_path)

# Verify JSON is valid
with open(out_path, "r", encoding="utf-8") as f:
    json.load(f)
print("JSON valid: OK")
